version: 2.1
orbs:
  node: circleci/node@1.1.6
  coverage-reporter: codacy/coverage-reporter@7.5.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            # - store_test_results:
            #     path: test-results
            - coverage-reporter/send_report
            - run: npm run build
            - run:
                name: Publish package
                command: npm run semantic-release || true
workflows:
  build-and-test:
    jobs:
      - build-and-test
